vim.cmd [[autocmd BufWritePre * %s/\s\+$//e]]
vim.cmd [[autocmd TermOpen * set nonu]]
vim.cmd [[autocmd TermOpen * startinsert]]
vim.cmd [[autocmd TermOpen * :DisableWhitespace]]
vim.cmd [[command! EditConfig edit ~/.config/nvim/init.lua]]
vim.cmd [[command! CloseWindow q]]
vim.cmd [[command! KillBuffer bd!]]
vim.cmd [[command! KillOtherBuffers %bdelete!|edit #|normal `"]]
vim.cmd [[command! VerticalSplit vsplit]]
vim.cmd [[command! HorizontalSplit split]]
vim.cmd [[command! OpenTerminal term]]
vim.cmd [[command! ExploreFiles Sexplore]]
vim.cmd [[command! SearchFiles Ag]]
vim.cmd [[command! GoToDefinition lua vim.lsp.buf.definition()]]
vim.cmd [[command! GoToReferences lua vim.lsp.buf.references()]]
vim.cmd [[command! FormatJson :%!jq .]]
vim.cmd [[command! LspClearLog :! rm /Users/pedrogutierrez/.local/state/nvim/lsp.log]]
vim.cmd [[command! LspClearElixirLs :! rm -rf .elixir_ls]]
vim.cmd [[command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>, '--ignore-dir={_build,deps}', fzf#vim#with_preview(), <bang>0)]]
